### ISSUE TITLE
wait for value

### ISSUE THREAD

**Issue by MrMoronIV** [AndriousSolutions/prefs#1]
I need to retrieve the locale before the app is built. Everything I tried so far is complaining about that SharedPreferences is not ready and I should try a Future instead, but I need to value before building the widget tree, how would I approach this?

**Comment by Andrious** [comment]
Would you supply your Github? Nothing like seeing the  code to understand what you're doing.
Possibly, using [mvc_application](https://pub.dev/packages/mvc_application), with its FutureBuilder will be your solution.

**Comment by Andrious** [comment]
No response. Closing issue.
