### ISSUE TITLE
No Prefs.containsKey('key_string') method

### ISSUE THREAD

**Issue by Sam-Guru-In-Training** [AndriousSolutions/prefs#3]
I guess if a key doesn't exist it will return Null when you try and get it's value, so you can test for this, but it's less clean than containsKey in classic SharedPreferences.

Anyway, thanks for the work.
Sam.

**Comment by Andrious** [comment]
Noted.  I'll look into it, thanks.

**Comment by Andrious** [comment]
Done.  Thanks, I didn't see that was missing strangely.
